# Generated by Django 5.1.5 on 2025-01-23 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_rename_blogcollection_blog_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='topic',
            new_name='blog',
        ),
    ]
